'use strict';
const fs = require('node:fs');
const os = require('os');
const url = require('url');
const path = require('path');

const cli = require('../../lib');

const nginxConfigPath = process.env.NGINX_CONFIG_PATH || '/etc/nginx';
const nginxProgramName = process.env.NGINX_PROGRAM_NAME || 'nginx';

// Matches the literal proxy_pass generated by Ghost-CLI < 1.31.0
const literalApProxyPass = /^([ \t]*)proxy_pass https:\/\/ap\.ghost\.org;$/gm;

// X-Forwarded-For header generated by Ghost-CLI < 1.31.0, and its replacement
const OLD_XFF_HEADER = 'proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;';
const NEW_XFF_HEADER = 'proxy_set_header X-Forwarded-For $remote_addr;';

function migrateSSL(ctx, migrateTask) {
    const acme = require('./acme');

    const parsedUrl = url.parse(ctx.instance.config.get('url'));
    const confFile = path.join(ctx.instance.dir, 'system', 'files', `${parsedUrl.hostname}-ssl.conf`);
    const rootPath = path.resolve(ctx.instance.dir, 'system', 'nginx-root');

    // Case to skip 1: SSL config for nginx does not exist
    if (!fs.existsSync(confFile)) {
        return migrateTask.skip('SSL config has not been set up for this domain');
    }

    const originalAcmePath = path.join(os.homedir(), '.acme.sh');
    const originalCertFolder = path.join(originalAcmePath, parsedUrl.hostname);

    // Case to skip 2: SSL cert doesn't exist in the original location for this domain
    if (!fs.existsSync(originalCertFolder)) {
        return migrateTask.skip('SSL cert does not exist for this domain');
    }

    const confFileContents = fs.readFileSync(confFile, {encoding: 'utf8'});
    const certCheck = new RegExp(`ssl_certificate ${originalCertFolder}/fullchain.cer;`);

    // Case to skip 3: SSL conf does not contain a cert config using the old LE cert
    if (!certCheck.test(confFileContents)) {
        return migrateTask.skip('LetsEncrypt SSL cert is not being used for this domain');
    }

    // 1. parse ~/.acme.sh/account.conf to get the email
    const accountConf = fs.readFileSync(path.join(originalAcmePath, 'account.conf'), {encoding: 'utf8'});
    const parsed = accountConf.match(/ACCOUNT_EMAIL='(.*)'\n/);

    if (!parsed) {
        throw new cli.errors.SystemError('Unable to parse letsencrypt account email');
    }

    return this.ui.listr([{
        // 2. install acme.sh in /etc/letsencrypt if that hasn't been done already
        title: 'Installing acme.sh in new location',
        task: (_ctx, task) => acme.install(this.ui, task)
    }, {
        // 3. run install cert for new acme.sh instance
        title: 'Regenerating SSL certificate in new location',
        task: () => acme.generate(this.ui, parsedUrl.hostname, rootPath, parsed[1], false)
    }, {
        // 4. Update cert locations in nginx-ssl.conf
        title: 'Updating nginx config',
        task: () => {
            const acmeFolder = path.join('/etc/letsencrypt', parsedUrl.hostname);
            const keyCheck = new RegExp(`ssl_certificate_key ${originalCertFolder}/${parsedUrl.hostname}.key;`);

            // Ensure here that we ONLY replace instances of the LetsEncrypt cert in the file,
            // that way we don't overwrite the cert config of other certs.
            const updated = fs.readFileSync(confFile, {encoding: 'utf8'})
                .replace(certCheck, `ssl_certificate ${path.join(acmeFolder, 'fullchain.cer')};`)
                .replace(keyCheck, `ssl_certificate_key ${path.join(acmeFolder, `${parsedUrl.hostname}.key`)};`);

            fs.writeFileSync(confFile, updated);
        }
    }, {
        title: 'Restarting Nginx',
        task: () => this.restartNginx()
    }, {
        // 5. run acme.sh --remove -d domain in old acme.sh directory to remove the old cert from renewal
        title: 'Disabling renewal for old certificate',
        task: () => acme.remove(parsedUrl.hostname, this.ui, originalAcmePath)
    }], false);
}

/**
 * Nginx resolves hostnames in literal proxy_pass directives when it loads its config,
 * so a momentary DNS outage (reboot, systemd-resolved restart) stops the whole site
 * from starting. Rewrite the ActivityPub locations of any existing config to resolve
 * ap.ghost.org per-request instead. See https://github.com/TryGhost/Ghost-CLI/issues/2044
 */
async function migrateActivityPubDns(ctx, migrateTask) {
    const {hostname} = url.parse(ctx.instance.config.get('url'));
    const sitesAvailable = path.join(nginxConfigPath, 'sites-available');

    const configs = [`${hostname}.conf`, `${hostname}-ssl.conf`]
        .filter(file => fs.existsSync(path.join(sitesAvailable, file)))
        .map(file => ({file, contents: fs.readFileSync(path.join(sitesAvailable, file), {encoding: 'utf8'})}))
        .filter(({contents}) => contents.match(literalApProxyPass));

    if (!configs.length) {
        return migrateTask.skip('Nginx config does not need updating');
    }

    const resolvers = this.getResolvers();
    const write = ({file, contents}) => this.template(ctx.instance, contents, 'nginx config', file, sitesAvailable);

    try {
        for (const {file, contents} of configs) {
            const updated = contents.replace(literalApProxyPass, (match, indent) => [
                `${indent}# Resolved per-request so nginx can still start when DNS is briefly unavailable (Ghost-CLI#2044)`,
                `${indent}resolver ${resolvers} valid=300s;`,
                `${indent}resolver_timeout 5s;`,
                `${indent}set $activitypub_upstream https://ap.ghost.org;`,
                `${indent}proxy_pass $activitypub_upstream;`
            ].join('\n'));

            await write({file, contents: updated});
        }

        await this.ui.sudo(`${nginxProgramName} -t`);
    } catch (error) {
        // Put the originals back so a partial or invalid rewrite can't take the site down
        for (const config of configs) {
            await write(config);
        }

        throw new cli.errors.CliError({
            message: 'Failed to update the ActivityPub section of your nginx config.',
            err: error
        });
    }

    await this.restartNginx();
}

/**
 * Ghost-CLI < 1.31.0 set X-Forwarded-For to $proxy_add_x_forwarded_for, which appends the
 * client address to whatever the client itself sent, letting a request spoof the chain.
 * Rewrite any existing config to send the real remote address instead.
 */
async function migrateXForwardedFor(ctx, migrateTask) {
    const {hostname} = url.parse(ctx.instance.config.get('url'));
    const sitesAvailable = path.join(nginxConfigPath, 'sites-available');

    const confFiles = [`${hostname}.conf`, `${hostname}-ssl.conf`]
        .map(file => path.join(sitesAvailable, file))
        .filter(file => fs.existsSync(file) && fs.readFileSync(file, {encoding: 'utf8'}).includes(OLD_XFF_HEADER));

    // Case to skip: no nginx config for this domain still sets the old header
    if (!confFiles.length) {
        return migrateTask.skip('X-Forwarded-For header is already up-to-date');
    }

    for (const file of confFiles) {
        await this.ui.sudo(`sed -i 's|${OLD_XFF_HEADER}|${NEW_XFF_HEADER}|' ${file}`);
    }

    await this.restartNginx();
}

module.exports = {
    migrateSSL: migrateSSL,
    migrateActivityPubDns: migrateActivityPubDns,
    migrateXForwardedFor: migrateXForwardedFor
};
