name: Unit Tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20.x, 22.x, 24.x]
    env:
      FORCE_COLOR: 1
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: pnpm/action-setup@08c4be7e2e672a47d11bd04269e27e5f3e8529cb # v6
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
        env:
          FORCE_COLOR: 0
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test
